macro HERO_SETTINGS_TEAM1 = {
    "general": {
        "abilityCooldown%": TEAM1_ABILITY_COOLDOWN_PCT
    }
}

macro HERO_SETTINGS_TEAM2 = {
    "bastion": {
        "secondaryFireCooldown%": BOSS_BASTION_SEC_FIRE_COOLDOWN_PCT,
        "secondaryFireKb%": BOSS_BASTION_SEC_FIRE_KB_PCT,
        "projectileSpeed%": BOSS_BASTION_PROJECTILE_SPEED_PCT,
        "enableInfiniteAmmo": BOSS_BASTION_INFINITE_AMMO,
        "health%": BOSS_BASTION_HEALTH_PCT
    },
    "general": {
        "damageReceived%": TEAM2_DAMAGE_RECEIVED_PCT,
        "abilityCooldown%": TEAM2_ABILITY_COOLDOWN_PCT,
        "health%": TEAM2_HEALTH_PCT
    }
}
